name: CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: 'echo Hello, world!'
      - name: Run a multi-line script
        run: >
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

          postman login --with-api-key
          PMAK-65ca0e5a2a67ac00015acf73-3acac16cbe307bbbd339e7f3fe2d8cf1a8

          postman collection run "27301606-83621e5d-445d-4e2d-9994-79e1f9ab78f9"
          -e "27301606-637b5725-cf05-4781-b1ae-71cd71dea91a"
